image: node:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install  # Instala las dependencias

test:
  stage: test
  script:
    - npm test  # Ejecuta tus pruebas Jest
  artifacts:
    paths:
      - node_modules/  # Caché para las dependencias
