variables:
    IMAGE_NAME: alanmad06/private-repo
    IMAGE_TAG: mastering-react-state

stages:
  - test
  - build
  - deploy

test:
  image: node:18.16.0
  stage: test
  before_script:
    - npm install
  script:
    - npm test  

build:
  stage: build
  image: docker:26.1.3
  services:
    - docker:26.1.3-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script: 
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  
deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
           #2
  script:  #sudo docker stop $(sudo docker ps -a -q) && sudo docker rm $(sudo docker ps -a -q) &&
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@159.54.148.245 "
        sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD &&
        sudo docker run -d -p 3001:3001 $IMAGE_NAME:$IMAGE_TAG"
