variables:
    IMAGE_NAME: alanmad06/private-repo
    IMAGE_TAG: mastering-react-state

stages:
  - test
  - build

test:
  image: node:18.16.0
  stage: test
  before_script:
    - npm install
  script:
    - npm test  

build:
  stage: build
  image: docker:26.1.3
  services:
    - docker:26.1.3-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script: 
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
